FROM alpine:3.19

WORKDIR /app

COPY order-service/order-api .
COPY ../initdb/migrations/order ./migrations
COPY order-service/configs/main.yaml ./configs/main.yaml

EXPOSE 8083 9093

CMD ["./order-api"]
