server:
  grpc_port: "9093"
  rest_port: "8080"

postgres:
  host: "postgres"
  port: "5432"

redis:
  host: "redis"
  port: "6379"

minio:
  client_port: "9000"
  server_port: "9001"
  internal_endpoint: "minio:9000"
  external_endpoint: "http://localhost:9000"

auth-service:
  host: "auth-service"
  port: "9091"

catalog-service:
  host: "catalog-service"
  port: "9092"

rabbitmq:
  host: "rabbitmq"
  port: "5672"
